name: SVV Validation Pipeline

on:
  push:
    branches:
      - main

jobs:

  validate-project:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Verify Folder Structure
        run: |
          test -d project-root/requirements
          test -d project-root/z-model
          test -d project-root/vdm
          test -d project-root/Alloy
          test -d project-root/Validation

      - name: Verify Required Files
        run: |
          test -f project-root/requirements/SRS.md
          test -f project-root/requirements/defect-taxonomy.md
          test -f project-root/requirements/github-issues.md
          test -f project-root/z-model/systemauth.zed
          test -f project-root/vdm/systemauth.vdmpp
          test -f project-root/Alloy/Systemauth.als

      - name: Generate Validation Report
        run: |
          echo "SVV Validation Successful"

      - name: Pipeline Success
        run: |
          echo "Pipeline Passed"
